import { ModuleRegistration, SubsystemRegistration } from "../types";

/**
 * HRM Subsystem Module Generator
 * Dynamically generates the IDS HRM subsystem structure with configurable parent IDs
 * Designed to be imported into the subsystem registration system
 */

/**
 * Base HRM module structure (without parent_module_id - to be injected dynamically)
 * This defines the hierarchy and relationships of all HRM modules
 */
export const hrmBaseModulesStructure: Omit<ModuleRegistration, "id" | "subsystem_id">[] = [
  {
    id: 1,
    subsystem_id: HRM_SUBSYSTEM_ID,
    parent_module_id: null,
    slug: "employee-admin",
    title: "Employee Admin",
    base_path: "/ids/hrm/employee-admin",
    status: "active",
    icon_name: "UserCog",
    sort: 0,
    subscription: null,
    subModules: [
      {
        id: 2,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 1,
        slug: "employee-admin-master-list",
        title: "Employee Admin Master List",
        base_path: "/ids/hrm/employee-admin/employee-admin-master-list",
        status: "active",
        icon_name: "Book",
        sort: 0,
        subscription: 1,
      },
      {
        id: 3,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 1,
        slug: "administrator",
        title: "Administrator",
        base_path: "/ids/hrm/employee-admin/administrator",
        status: "active",
        icon_name: "UserCog",
        sort: 2,
        subscription: null,
        subModules: [
          {
            id: 7,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 3,
            slug: "department-schedule",
            title: "Department Schedule",
            base_path: "/ids/hrm/employee-admin/administrator/department-schedule",
            status: "active",
            icon_name: "CalendarDays",
            sort: 0,
            subscription: null,
          },
          {
            id: 8,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 3,
            slug: "on-call",
            title: "On Call",
            base_path: "/ids/hrm/employee-admin/administrator/on-call",
            status: "active",
            icon_name: "Smartphone",
            sort: 1,
            subscription: null,
          },
        ],
      },
      {
        id: 9,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 1,
        slug: "structure",
        title: "Structure",
        base_path: "/ids/hrm/employee-admin/structure",
        status: "active",
        icon_name: "Layers",
        sort: 1,
        subscription: null,
        subModules: [
          {
            id: 10,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 9,
            slug: "division",
            title: "Division",
            base_path: "/ids/hrm/employee-admin/structure/division",
            status: "active",
            icon_name: "Layers",
            sort: 0,
            subscription: null,
          },
          {
            id: 11,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 9,
            slug: "company-profile",
            title: "Company Profile",
            base_path: "/ids/hrm/employee-admin/structure/company-profile",
            status: "active",
            icon_name: "IdCard",
            sort: 1,
            subscription: null,
          },
          {
            id: 12,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 9,
            slug: "department",
            title: "Department",
            base_path: "/ids/hrm/employee-admin/structure/department",
            status: "active",
            icon_name: "GanttChartSquare",
            sort: 2,
            subscription: null,
          },
          {
            id: 14,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 9,
            slug: "department-accounts",
            title: "Department Accounts",
            base_path: "/ids/hrm/employee-admin/structure/department-accounts",
            status: "active",
            icon_name: "Users",
            sort: 3,
            subscription: null,
          },
          {
            id: 15,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 9,
            slug: "role-management",
            title: "Role Management",
            base_path: "/ids/hrm/employee-admin/structure/role-management",
            status: "active",
            icon_name: "Users",
            sort: 4,
            subscription: null,
          },
          {
            id: 16,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 9,
            slug: "operation",
            title: "Operation",
            base_path: "/ids/hrm/employee-admin/structure/operation",
            status: "active",
            icon_name: "Network",
            sort: 5,
            subscription: null,
          },
          {
            id: 17,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 9,
            slug: "industry",
            title: "Industry",
            base_path: "/ids/hrm/employee-admin/structure/industry",
            status: "active",
            icon_name: "Layers",
            sort: 6,
            subscription: null,
          },
        ],
      },
      {
        id: 18,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 1,
        slug: "sales-management",
        title: "Sales Management",
        base_path: "/ids/hrm/employee-admin/sales-management",
        status: "active",
        icon_name: "BarChartBig",
        sort: 3,
        subscription: null,
        subModules: [
          {
            id: 20,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 18,
            slug: "salesman-creation",
            title: "Salesman Creation",
            base_path: "/ids/hrm/employee-admin/sales-management/salesman-creation",
            status: "active",
            icon_name: "Edit",
            sort: 0,
            subscription: null,
          },
          {
            id: 21,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 18,
            slug: "salesman-qr-code",
            title: "Salesman QR Code",
            base_path: "/ids/hrm/employee-admin/sales-management/salesman-qr-code",
            status: "active",
            icon_name: "Fingerprint",
            sort: 1,
            subscription: null,
          },
        ],
      },
      {
        id: 19,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 1,
        slug: "approval",
        title: "Approval",
        base_path: "/ids/hrm/employee-admin/approval",
        status: "active",
        icon_name: "CheckCheck",
        sort: 4,
        subscription: null,
        subModules: [
          {
            id: 22,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 19,
            slug: "attendance-approval",
            title: "Attendance Approval",
            base_path: "/ids/hrm/employee-admin/approval/attendance-approval",
            status: "active",
            icon_name: "ClipboardCheck",
            sort: 0,
            subscription: null,
          },
          {
            id: 23,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 19,
            slug: "overtime-request",
            title: "Overtime Request",
            base_path: "/ids/hrm/employee-admin/approval/overtime-request",
            status: "active",
            icon_name: "AlarmClockCheck",
            sort: 1,
            subscription: null,
          },
          {
            id: 24,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 19,
            slug: "undertime-request",
            title: "Undertime Request",
            base_path: "/ids/hrm/employee-admin/approval/undertime-request",
            status: "active",
            icon_name: "AlarmClockCheck",
            sort: 2,
            subscription: null,
          },
          {
            id: 25,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 19,
            slug: "leave-request",
            title: "Leave Request",
            base_path: "/ids/hrm/employee-admin/approval/leave-request",
            status: "active",
            icon_name: "AlarmClockOff",
            sort: 3,
            subscription: null,
          },
        ],
      },
      {
        id: 26,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 1,
        slug: "report",
        title: "Report",
        base_path: "/ids/hrm/employee-admin/report",
        status: "active",
        icon_name: "AlertCircle",
        sort: 5,
        subscription: null,
        subModules: [
          {
            id: 27,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 26,
            slug: "overtime-report",
            title: "Overtime Report",
            base_path: "/ids/hrm/employee-admin/report/overtime-report",
            status: "active",
            icon_name: "FilePlus",
            sort: 0,
            subscription: null,
          },
          {
            id: 28,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 26,
            slug: "undertime-report",
            title: "Undertime Report",
            base_path: "/ids/hrm/employee-admin/report/undertime-report",
            status: "active",
            icon_name: "FileMinus",
            sort: 1,
            subscription: null,
          },
        ],
      },
    ],
  },
  {
    id: 4,
    subsystem_id: HRM_SUBSYSTEM_ID,
    parent_module_id: null,
    slug: "user-configuration",
    title: "User Configuration",
    base_path: "/ids/hrm/user-configuration",
    status: "active",
    icon_name: "UserCog",
    sort: 2,
    subscription: 4,
  },
  {
    id: 5,
    subsystem_id: HRM_SUBSYSTEM_ID,
    parent_module_id: null,
    slug: "subsystem-registration",
    title: "Subsystem Registration",
    base_path: "/ids/hrm/subsystem-registration",
    status: "active",
    icon_name: "Boxes",
    sort: 1,
    subscription: 2,
  },
  {
    id: 6,
    subsystem_id: HRM_SUBSYSTEM_ID,
    parent_module_id: null,
    slug: "pdf-layout",
    title: "PDF Layout",
    base_path: "/ids/hrm/pdf-layout",
    status: "active",
    icon_name: "Layout",
    sort: 3,
    subscription: 4,
  },
  {
    id: 29,
    subsystem_id: HRM_SUBSYSTEM_ID,
    parent_module_id: null,
    slug: "workforce",
    title: "Workforce",
    base_path: "/ids/hrm/workforce",
    status: "active",
    icon_name: "Users",
    sort: 4,
    subscription: null,
    subModules: [
      {
        id: 30,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 29,
        slug: "attendance-report",
        title: "Attendance Report",
        base_path: "/ids/hrm/workforce/attendance-report",
        status: "active",
        icon_name: "ClipboardList",
        sort: 0,
        subscription: null,
        subModules: [
          {
            id: 31,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 30,
            slug: "todays-report",
            title: "Todays Report",
            base_path: "/ids/hrm/workforce/attendance-report/todays-report",
            status: "active",
            icon_name: "CalendarCheck",
            sort: 0,
            subscription: null,
          },
          {
            id: 32,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 30,
            slug: "employee-report",
            title: "Employee Report",
            base_path: "/ids/hrm/workforce/attendance-report/employee-report",
            status: "active",
            icon_name: "UserCheck",
            sort: 1,
            subscription: null,
          },
          {
            id: 33,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 30,
            slug: "department-report",
            title: "Department Report",
            base_path: "/ids/hrm/workforce/attendance-report/department-report",
            status: "active",
            icon_name: "ListChecks",
            sort: 2,
            subscription: null,
          },
          {
            id: 34,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 30,
            slug: "logistics-report",
            title: "Logistics Report",
            base_path: "/ids/hrm/workforce/attendance-report/logistics-report",
            status: "active",
            icon_name: "Boxes",
            sort: 3,
            subscription: null,
          },
        ],
      },
      {
        id: 35,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 29,
        slug: "attendance-management",
        title: "Attendance Management",
        base_path: "/ids/hrm/workforce/attendance-management",
        status: "comingSoon",
        icon_name: "Contact",
        sort: 1,
        subscription: null,
      },
      {
        id: 36,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 29,
        slug: "job-orders",
        title: "Job Orders",
        base_path: "/ids/hrm/workforce/job-orders",
        status: "comingSoon",
        icon_name: "FileCheck",
        sort: 2,
        subscription: null,
        subModules: [
          {
            id: 37,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 36,
            slug: "application-management",
            title: "Application Management",
            base_path: "/ids/hrm/workforce/job-orders/application-management",
            status: "comingSoon",
            icon_name: "Users",
            sort: 0,
            subscription: null,
          },
        ],
      },
      {
        id: 38,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 29,
        slug: "asset-tagging",
        title: "Asset Tagging",
        base_path: "/ids/hrm/workforce/asset-tagging",
        status: "comingSoon",
        icon_name: "Maximize",
        sort: 3,
        subscription: null,
      },
      {
        id: 39,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 29,
        slug: "asset-investigation",
        title: "Asset Investigation",
        base_path: "/ids/hrm/workforce/asset-investigation",
        status: "comingSoon",
        icon_name: "Locate",
        sort: 4,
        subscription: null,
      },
    ],
  },
  {
    id: 40,
    subsystem_id: HRM_SUBSYSTEM_ID,
    parent_module_id: null,
    slug: "communications",
    title: "Communications",
    base_path: "/ids/hrm/communications",
    status: "comingSoon",
    icon_name: "Users",
    sort: 5,
    subscription: null,
    subModules: [
      {
        id: 42,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 40,
        slug: "policies",
        title: "Policies",
        base_path: "/ids/hrm/communications/policies",
        status: "comingSoon",
        icon_name: "BookOpen",
        sort: 0,
        subscription: null,
      },
      {
        id: 43,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 40,
        slug: "memorandums",
        title: "Memorandums",
        base_path: "/ids/hrm/communications/memorandums",
        status: "comingSoon",
        icon_name: "File",
        sort: 1,
        subscription: null,
      },
      {
        id: 44,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 40,
        slug: "notices",
        title: "Notices",
        base_path: "/ids/hrm/communications/notices",
        status: "comingSoon",
        icon_name: "AlertOctagon",
        sort: 2,
        subscription: null,
        subModules: [
          {
            id: 45,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 44,
            slug: "nte",
            title: "NTE",
            base_path: "/ids/hrm/communications/notices/nte",
            status: "comingSoon",
            icon_name: "AlertCircle",
            sort: 0,
            subscription: null,
          },
          {
            id: 46,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 44,
            slug: "nod",
            title: "NOD",
            base_path: "/ids/hrm/communications/notices/nod",
            status: "comingSoon",
            icon_name: "AlertCircle",
            sort: 1,
            subscription: null,
          },
          {
            id: 47,
            subsystem_id: HRM_SUBSYSTEM_ID,
            parent_module_id: 44,
            slug: "care",
            title: "CARE",
            base_path: "/ids/hrm/communications/notices/care",
            status: "comingSoon",
            icon_name: "ShieldAlert",
            sort: 2,
            subscription: null,
          },
        ],
      },
      {
        id: 48,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 40,
        slug: "announcement",
        title: "Announcement",
        base_path: "/ids/hrm/communications/announcement",
        status: "comingSoon",
        icon_name: "Bell",
        sort: 3,
        subscription: null,
      },
      {
        id: 49,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 40,
        slug: "cooperatives",
        title: "Cooperatives",
        base_path: "/ids/hrm/communications/cooperatives",
        status: "comingSoon",
        icon_name: "Briefcase",
        sort: 4,
        subscription: null,
      },
    ],
  },
  {
    id: 41,
    subsystem_id: HRM_SUBSYSTEM_ID,
    parent_module_id: null,
    slug: "file-management",
    title: "File Management",
    base_path: "/ids/hrm/file-management",
    status: "active",
    icon_name: "Archive",
    sort: 6,
    subscription: null,
    subModules: [
      {
        id: 50,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 41,
        slug: "employee-file-record-type",
        title: "Employee File Record Type",
        base_path: "/ids/hrm/file-management/employee-file-record-type",
        status: "active",
        icon_name: "FileSearch",
        sort: 0,
        subscription: null,
      },
      {
        id: 51,
        subsystem_id: HRM_SUBSYSTEM_ID,
        parent_module_id: 41,
        slug: "employee-file-record-list",
        title: "Employee File Record List",
        base_path: "/ids/hrm/file-management/employee-file-record-list",
        status: "active",
        icon_name: "FileText",
        sort: 1,
        subscription: null,
      },
    ],
  },
];

export const hrmSubsystemData: SubsystemRegistration = {
  id: HRM_SUBSYSTEM_ID,
  slug: "hrm",
  title: "Human Resource Management",
  subtitle: "Manage employees, departments, and organizational structure",
  base_path: "/ids/hrm",
  icon_name: "Users",
  status: "active",
  category: "Operations",
  tag: "hrm",
  modules: hrmModulesData,
};

/**
 * Helper function to get a flattened list of all modules (for bulk operations)
 */
export function getFlattenedModules(modules: ModuleRegistration[] = hrmModulesData): ModuleRegistration[] {
  const flattened: ModuleRegistration[] = [];
  
  const traverse = (items: ModuleRegistration[]) => {
    items.forEach((item) => {
      const { subModules, ...itemWithoutSub } = item;
      flattened.push(itemWithoutSub as ModuleRegistration);
      if (subModules && subModules.length > 0) {
        traverse(subModules);
      }
    });
  };
  
  traverse(modules);
  return flattened;
}
